# Generated by Django 4.2.4 on 2023-08-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_drf', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sectionId',
            field=models.CharField(default='varios', max_length=100),
        ),
    ]
